micronaut:
  application:
    name: be
---
#tag::security[]
micronaut:
  security:
    enabled: true
    ip-patterns: []
    authentication: bearer
    endpoints:
      login:
        enabled: true
        path: /login
        defaultSuccessUrl: /login-success
        failureUrl: /login-failure
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: d38d58F4ej456Dn364ifnX47rh4z47dn4zdh5Mf
    reject-not-found: false
#end::security[]
---
#tag::refresh[]
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: gh37d57f47dXh47dh4G038f47dj4U7d79f7MQ
#end::refresh[]
---
#tag::datasources[]
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/emsdevdb
    username: emsdev
    password: 1q2w3e4r5t6z7u8i9o0p
    db-type: postgres
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    schema: be
    data-source-properties:
      ApplicationName: "ems-be (version 1.0)"
#end::datasources[]
---
#tag::jpa[]
jpa:
  default:
    entity-scan:
      packages:
        - com.ems.be
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        implicit_naming_strategy: jpa
        show_sql: false
#end::jpa[]
---
#tag::netty[]
netty:
  default:
    allocator:
      max-order: 3
#end::netty[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true
#end::flyway[]