version: '3.1'

services:
  postgres:
    image: postgres:12.4
    restart: on-failure
    environment:
      POSTGRES_USER: emsdev
      POSTGRES_PASSWORD: 1q2w3e4r5t6z7u8i9o0p
      POSTGRES_DB: emsdevdb
    ports:
      - 5432:5432
    volumes:
      - ./dump:/docker-entrypoint-initdb.d